export { TabBar } from "./TabBar";
export {
  MAX_PANES_PER_TAB,
  useTabs,
  type Tab,
  type TerminalTab,
  type EditorTab,
  type PreviewTab,
  type MarkdownTab,
  type ImageTab,
  type LogTab,
  type DataTab,
  type S3Tab,
  type AiDiffTab,
  type GitDiffTab,
  type GitHistoryTab,
  type GitCommitFileDiffTab,
  type BunqueueTab,
  type DockerDetailTab,
  type DockerTab,
  type SshTab,
  type AnalyticsTab,
  type OtelTab,
  type KvTab,
  type CcusageTab,
  type GithubFeedTab,
  type ProjectsTab,
  type ProjectDetailTab,
  type AiDiffStatus,
  type TabPatch,
} from "./lib/useTabs";
export { useWorkspaceCwd } from "./lib/useWorkspaceCwd";
export { useStableTabSlice } from "./lib/useStableTabSlice";
