//! S3 file browser backend.
//!
//! Powers `src/modules/s3` (the S3 browser tab): list buckets/prefixes/objects,
//! fetch small objects as bytes for inline preview (json/image/pdf), download an
//! object to a temp cache (so the local `data_*` engine can open formats that
//! can't be range-paged over S3 — SQLite, and CSV without a row index), and
//! page Parquet **directly from S3** via the async object-store reader so a
//! multi-GB file is never fully downloaded just to show a page.
//!
//! Credentials live in the cross-platform [`secrets`](super::secrets) store
//! (`service = "s3"`, `account = <connection id>`, `password = JSON`). Only the
//! *non-secret* connection metadata (name, region, endpoint, optional default
//! bucket/prefix) is persisted in a plain JSON file under the app data dir —
//! the access key id and secret never touch that file or any log line.

use std::path::PathBuf;
use std::sync::Mutex;

use serde::{Deserialize, Serialize};
use tauri::{AppHandle, Manager};

use super::fs::data::{DataPreview, SortSpec};
use super::secrets::SecretsState;

/// `keyring`/secrets service namespace for S3 credential blobs.
const SECRET_SERVICE: &str = "s3";

/// Format an AWS SDK error with its full `source()` chain. `SdkError`'s own
/// `Display` only prints the top-level category (e.g. "service error"); the
/// actionable detail — the S3 error code/message such as `PermanentRedirect`
/// (bucket in another region) or `AccessDenied` — lives in the chained source.
/// `DisplayErrorContext` flattens the whole chain into one string.
fn aws_err<E: std::error::Error>(ctx: &str, e: E) -> String {
    use aws_smithy_types::error::display::DisplayErrorContext;
    format!("{ctx}: {}", DisplayErrorContext(&e))
}

/// Flatten an arbitrary IPC-supplied string into a single safe path component:
/// no separators, no `..`, no drive colons. Used for the connection id, bucket,
/// and object key when building the local cache path so a crafted value can
/// never escape the cache root (Windows `Path::join` of an absolute or `..`
/// component would otherwise walk out of the directory).
fn safe_component(s: &str) -> String {
    let cleaned: String = s
        .chars()
        .map(|c| match c {
            '/' | '\\' | ':' | '\0' => '_',
            c => c,
        })
        .collect();
    // Collapse any remaining `..` so even after the char map nothing traverses.
    let cleaned = cleaned.replace("..", "__");
    if cleaned.is_empty() {
        "_".to_string()
    } else {
        cleaned
    }
}

/// Cap on a single inline-preview byte fetch (json/image/pdf). Larger objects
/// must go through the temp-cache download path instead of being shipped over
/// IPC in one base64 payload.
const MAX_INLINE_BYTES: u64 = 32 * 1024 * 1024;

/// Hard cap on objects returned in one `s3_list` page so a giant prefix can't
/// produce an unbounded IPC payload. The UI lazily expands a node at a time.
const LIST_PAGE_SIZE: i32 = 1000;

// ---------------------------------------------------------------------------
// Connection model
// ---------------------------------------------------------------------------

/// Non-secret connection metadata, persisted to `s3_connections.json`. The
/// secret half (`access_key_id` + `secret_access_key` + optional session token)
/// is stored separately in the OS secret store, keyed by `id`.
#[derive(Serialize, Deserialize, Clone, Debug, PartialEq)]
pub struct S3Connection {
    /// Stable opaque id (also the secrets `account`). Generated by the UI.
    pub id: String,
    /// User-facing label.
    pub name: String,
    /// AWS region (e.g. `us-east-1`). Required even for S3-compatible stores;
    /// many accept any value when an endpoint is set.
    pub region: String,
    /// Custom endpoint URL for S3-compatible stores (MinIO/R2/Wasabi). `None`
    /// uses the real AWS endpoint for `region`.
    #[serde(default)]
    pub endpoint: Option<String>,
    /// Force path-style addressing (`endpoint/bucket/key`) instead of
    /// virtual-host (`bucket.endpoint/key`). Needed by most MinIO setups.
    #[serde(default)]
    pub force_path_style: bool,
    /// Optional default bucket to focus the tree on.
    #[serde(default)]
    pub bucket: Option<String>,
}

/// The secret half kept in the OS secret store as a JSON blob.
#[derive(Serialize, Deserialize, Clone, Debug)]
struct S3Secret {
    access_key_id: String,
    secret_access_key: String,
    #[serde(default)]
    session_token: Option<String>,
}

/// A full connection (metadata + secret) used to build a client. Never
/// serialized back to the frontend.
struct ResolvedConnection {
    meta: S3Connection,
    secret: S3Secret,
}

#[derive(Default)]
pub struct S3State {
    /// Process cache of the persisted metadata list, lazily loaded.
    conns: Mutex<Option<Vec<S3Connection>>>,
}

// ---------------------------------------------------------------------------
// Metadata persistence (non-secret)
// ---------------------------------------------------------------------------

fn meta_path(app: &AppHandle) -> Result<PathBuf, String> {
    let dir = app.path().app_local_data_dir().map_err(|e| e.to_string())?;
    std::fs::create_dir_all(&dir).map_err(|e| e.to_string())?;
    Ok(dir.join("s3_connections.json"))
}

fn read_meta(app: &AppHandle) -> Result<Vec<S3Connection>, String> {
    let p = meta_path(app)?;
    if !p.exists() {
        return Ok(Vec::new());
    }
    let bytes = std::fs::read(&p).map_err(|e| e.to_string())?;
    serde_json::from_slice(&bytes).map_err(|e| e.to_string())
}

fn write_meta(app: &AppHandle, list: &[S3Connection]) -> Result<(), String> {
    let p = meta_path(app)?;
    let tmp = p.with_extension("json.tmp");
    let bytes = serde_json::to_vec_pretty(list).map_err(|e| e.to_string())?;
    std::fs::write(&tmp, &bytes).map_err(|e| e.to_string())?;
    std::fs::rename(&tmp, &p).map_err(|e| e.to_string())?;
    Ok(())
}

/// Load the metadata list into the process cache once, then run `f` against it.
fn with_conns<F, R>(app: &AppHandle, state: &S3State, f: F) -> Result<R, String>
where
    F: FnOnce(&mut Vec<S3Connection>) -> R,
{
    let mut guard = state.conns.lock().map_err(|e| e.to_string())?;
    if guard.is_none() {
        *guard = Some(read_meta(app)?);
    }
    Ok(f(guard.as_mut().expect("cache initialized above")))
}

// ---------------------------------------------------------------------------
// Secret access (delegates to the platform secret store)
// ---------------------------------------------------------------------------

async fn load_secret(
    app: &AppHandle,
    secrets: &tauri::State<'_, SecretsState>,
    id: &str,
) -> Result<S3Secret, String> {
    let raw = super::secrets::secrets_get(
        app.clone(),
        secrets.clone(),
        SECRET_SERVICE.to_string(),
        id.to_string(),
    )
    .await?
    .ok_or_else(|| format!("no stored credentials for connection {id}"))?;
    serde_json::from_str(&raw).map_err(|e| format!("corrupt s3 secret: {e}"))
}

async fn resolve(
    app: &AppHandle,
    state: &S3State,
    secrets: &tauri::State<'_, SecretsState>,
    id: &str,
) -> Result<ResolvedConnection, String> {
    let meta = with_conns(app, state, |list| {
        list.iter().find(|c| c.id == id).cloned()
    })?
    .ok_or_else(|| format!("unknown connection {id}"))?;
    let secret = load_secret(app, secrets, id).await?;
    Ok(ResolvedConnection { meta, secret })
}

// ---------------------------------------------------------------------------
// Client builders
// ---------------------------------------------------------------------------

/// Build an `aws-sdk-s3` client used for listing and byte fetches.
async fn sdk_client(conn: &ResolvedConnection) -> aws_sdk_s3::Client {
    use aws_sdk_s3::config::{Credentials, Region};

    let creds = Credentials::new(
        conn.secret.access_key_id.clone(),
        conn.secret.secret_access_key.clone(),
        conn.secret.session_token.clone(),
        None,
        "terax-s3",
    );

    let mut builder = aws_sdk_s3::config::Builder::new()
        .behavior_version(aws_sdk_s3::config::BehaviorVersion::latest())
        .region(Region::new(conn.meta.region.clone()))
        .credentials_provider(creds);

    if let Some(ep) = &conn.meta.endpoint {
        builder = builder.endpoint_url(ep.clone());
    }
    if conn.meta.force_path_style {
        builder = builder.force_path_style(true);
    }

    aws_sdk_s3::Client::from_conf(builder.build())
}

/// Build an `object_store` S3 store for the async parquet ranged reader.
fn object_store(
    conn: &ResolvedConnection,
    bucket: &str,
) -> Result<object_store::aws::AmazonS3, String> {
    use object_store::aws::AmazonS3Builder;

    let mut b = AmazonS3Builder::new()
        .with_bucket_name(bucket)
        .with_region(&conn.meta.region)
        .with_access_key_id(&conn.secret.access_key_id)
        .with_secret_access_key(&conn.secret.secret_access_key);

    if let Some(ep) = &conn.meta.endpoint {
        b = b.with_endpoint(ep).with_allow_http(ep.starts_with("http://"));
    }
    if conn.meta.force_path_style {
        b = b.with_virtual_hosted_style_request(false);
    }
    if let Some(tok) = &conn.secret.session_token {
        b = b.with_token(tok);
    }

    b.build().map_err(|e| format!("object_store: {e}"))
}

// ---------------------------------------------------------------------------
// Connection CRUD commands
// ---------------------------------------------------------------------------

/// List configured connections (metadata only; no secrets).
#[tauri::command]
pub fn s3_list_connections(
    app: AppHandle,
    state: tauri::State<'_, S3State>,
) -> Result<Vec<S3Connection>, String> {
    with_conns(&app, &state, |list| list.clone())
}

/// Create or update a connection. `access_key_id`/`secret_access_key` are
/// written to the OS secret store; the rest is persisted as metadata.
#[tauri::command]
pub async fn s3_save_connection(
    app: AppHandle,
    state: tauri::State<'_, S3State>,
    secrets: tauri::State<'_, SecretsState>,
    conn: S3Connection,
    access_key_id: String,
    secret_access_key: String,
    session_token: Option<String>,
) -> Result<(), String> {
    let secret = S3Secret {
        access_key_id,
        secret_access_key,
        session_token,
    };
    let blob = serde_json::to_string(&secret).map_err(|e| e.to_string())?;
    super::secrets::secrets_set(
        app.clone(),
        secrets.clone(),
        SECRET_SERVICE.to_string(),
        conn.id.clone(),
        blob,
    )
    .await?;

    let snapshot = with_conns(&app, &state, |list| {
        if let Some(slot) = list.iter_mut().find(|c| c.id == conn.id) {
            *slot = conn.clone();
        } else {
            list.push(conn.clone());
        }
        list.clone()
    })?;
    write_meta(&app, &snapshot)
}

/// Delete a connection and its stored credentials.
#[tauri::command]
pub async fn s3_delete_connection(
    app: AppHandle,
    state: tauri::State<'_, S3State>,
    secrets: tauri::State<'_, SecretsState>,
    id: String,
) -> Result<(), String> {
    super::secrets::secrets_delete(
        app.clone(),
        secrets.clone(),
        SECRET_SERVICE.to_string(),
        id.clone(),
    )
    .await?;
    let snapshot = with_conns(&app, &state, |list| {
        list.retain(|c| c.id != id);
        list.clone()
    })?;
    write_meta(&app, &snapshot)
}

// ---------------------------------------------------------------------------
// Listing
// ---------------------------------------------------------------------------

/// A child node of a listing: either a sub-prefix ("folder") or an object.
#[derive(Serialize, Debug)]
pub struct S3Entry {
    /// Display name (last path segment, prefixes keep the trailing `/`).
    pub name: String,
    /// Full key (objects) or prefix (folders) relative to the bucket.
    pub key: String,
    pub is_prefix: bool,
    /// Object size in bytes; `None` for prefixes.
    pub size: Option<i64>,
}

/// List the immediate children of `prefix` in `bucket` (delimiter `/`), so the
/// UI can lazily expand one tree level at a time. An empty `bucket` lists the
/// account's buckets instead.
#[tauri::command]
pub async fn s3_list(
    app: AppHandle,
    state: tauri::State<'_, S3State>,
    secrets: tauri::State<'_, SecretsState>,
    id: String,
    bucket: String,
    prefix: String,
) -> Result<Vec<S3Entry>, String> {
    let conn = resolve(&app, &state, &secrets, &id).await?;
    let client = sdk_client(&conn).await;

    // Bucket-level listing.
    if bucket.is_empty() {
        let out = client
            .list_buckets()
            .send()
            .await
            .map_err(|e| aws_err("list buckets", e))?;
        let mut entries: Vec<S3Entry> = out
            .buckets()
            .iter()
            .filter_map(|b| b.name().map(|n| n.to_string()))
            .map(|name| S3Entry {
                key: name.clone(),
                name,
                is_prefix: true,
                size: None,
            })
            .collect();
        entries.sort_by(|a, b| a.name.cmp(&b.name));
        return Ok(entries);
    }

    let out = client
        .list_objects_v2()
        .bucket(&bucket)
        .prefix(&prefix)
        .delimiter("/")
        .max_keys(LIST_PAGE_SIZE)
        .send()
        .await
        .map_err(|e| aws_err("list objects", e))?;

    let mut entries: Vec<S3Entry> = Vec::new();

    // Sub-prefixes ("folders").
    for cp in out.common_prefixes() {
        if let Some(p) = cp.prefix() {
            let trimmed = p.strip_suffix('/').unwrap_or(p);
            let name = trimmed.rsplit('/').next().unwrap_or(trimmed).to_string();
            entries.push(S3Entry {
                name: format!("{name}/"),
                key: p.to_string(),
                is_prefix: true,
                size: None,
            });
        }
    }
    // Objects at this level (skip the prefix placeholder key itself).
    for obj in out.contents() {
        if let Some(k) = obj.key() {
            if k == prefix {
                continue;
            }
            let name = k.rsplit('/').next().unwrap_or(k).to_string();
            entries.push(S3Entry {
                name,
                key: k.to_string(),
                is_prefix: false,
                size: obj.size(),
            });
        }
    }
    Ok(entries)
}

// ---------------------------------------------------------------------------
// Byte fetch (inline preview)
// ---------------------------------------------------------------------------

/// Bytes of a small object for inline preview, base64-encoded for the JSON IPC
/// boundary. Rejects objects over [`MAX_INLINE_BYTES`] — those should use the
/// temp-cache download path.
#[derive(Serialize, Debug)]
pub struct S3Bytes {
    /// base64 of the raw object bytes.
    pub base64: String,
    /// `Content-Type` reported by S3, if any.
    pub content_type: Option<String>,
    pub size: i64,
}

#[tauri::command]
pub async fn s3_get_object_bytes(
    app: AppHandle,
    state: tauri::State<'_, S3State>,
    secrets: tauri::State<'_, SecretsState>,
    id: String,
    bucket: String,
    key: String,
) -> Result<S3Bytes, String> {
    let conn = resolve(&app, &state, &secrets, &id).await?;
    let client = sdk_client(&conn).await;

    let out = client
        .get_object()
        .bucket(&bucket)
        .key(&key)
        .send()
        .await
        .map_err(|e| aws_err("get object", e))?;

    let size = out.content_length().unwrap_or(0);
    if size as u64 > MAX_INLINE_BYTES {
        return Err(format!(
            "object is {size} bytes; too large for inline preview (max {MAX_INLINE_BYTES})"
        ));
    }
    let content_type = out.content_type().map(|s| s.to_string());
    let data = out
        .body
        .collect()
        .await
        .map_err(|e| format!("read body: {e}"))?
        .into_bytes();

    Ok(S3Bytes {
        base64: base64_encode(&data),
        content_type,
        size: data.len() as i64,
    })
}

// ---------------------------------------------------------------------------
// Temp-cache download (formats that can't be ranged over S3)
// ---------------------------------------------------------------------------

/// Download an object to a stable temp path keyed by connection/bucket/key and
/// return the local path. Reused on subsequent opens (the cache file persists
/// for the process lifetime). SQLite (random-access) and CSV (no row index) use
/// this so the local `data_*` engine can open them.
#[tauri::command]
pub async fn s3_download_to_cache(
    app: AppHandle,
    state: tauri::State<'_, S3State>,
    secrets: tauri::State<'_, SecretsState>,
    id: String,
    bucket: String,
    key: String,
) -> Result<String, String> {
    use tokio::io::AsyncWriteExt;

    let conn = resolve(&app, &state, &secrets, &id).await?;
    let client = sdk_client(&conn).await;

    let dir = app
        .path()
        .app_cache_dir()
        .map_err(|e| e.to_string())?
        .join("s3-cache")
        .join(safe_component(&id))
        .join(safe_component(&bucket));
    tokio::fs::create_dir_all(&dir)
        .await
        .map_err(|e| e.to_string())?;
    // Flatten the key to a single filename, preserving the extension so the FE
    // format detector still recognizes it.
    let fname = safe_component(&key);
    let dest = dir.join(&fname);

    let mut out = client
        .get_object()
        .bucket(&bucket)
        .key(&key)
        .send()
        .await
        .map_err(|e| aws_err("get object", e))?;

    let mut file = tokio::fs::File::create(&dest)
        .await
        .map_err(|e| format!("create cache file: {e}"))?;
    while let Some(chunk) = out
        .body
        .try_next()
        .await
        .map_err(|e| format!("download: {e}"))?
    {
        file.write_all(&chunk).await.map_err(|e| e.to_string())?;
    }
    file.flush().await.map_err(|e| e.to_string())?;

    Ok(super::fs::to_canon(&dest))
}

// ---------------------------------------------------------------------------
// Parquet — ranged paging directly from S3
// ---------------------------------------------------------------------------

/// Page a Parquet object **without downloading the whole file**: the async
/// object-store reader fetches only the row groups / byte ranges the requested
/// window touches. Mirrors `data_parquet_preview`'s wire format so the same
/// `DataPane` renders both local and S3 parquet. Search/sort are intentionally
/// unsupported here (they require a full scan, which defeats ranged reads — the
/// UI should fall back to the temp-cache path for those).
#[tauri::command]
pub async fn s3_parquet_preview(
    app: AppHandle,
    state: tauri::State<'_, S3State>,
    secrets: tauri::State<'_, SecretsState>,
    id: String,
    bucket: String,
    key: String,
    limit: u32,
    offset: u32,
    _search: Option<String>,
    _sort: Option<SortSpec>,
) -> Result<DataPreview, String> {
    use futures_util::StreamExt;
    use object_store::ObjectStore;
    use parquet::arrow::arrow_reader::ArrowReaderMetadata;
    use parquet::arrow::async_reader::{ParquetObjectReader, ParquetRecordBatchStreamBuilder};

    let conn = resolve(&app, &state, &secrets, &id).await?;
    let store = std::sync::Arc::new(object_store(&conn, &bucket)?);
    let path = object_store::path::Path::from(key.as_str());

    let meta = store
        .head(&path)
        .await
        .map_err(|e| format!("stat object: {e}"))?;
    let reader = ParquetObjectReader::new(store, meta);

    let arrow_meta = ArrowReaderMetadata::load_async(
        &mut reader.clone(),
        Default::default(),
    )
    .await
    .map_err(|e| format!("parquet meta: {e}"))?;

    let file_total = arrow_meta
        .metadata()
        .file_metadata()
        .num_rows()
        .max(0) as u64;

    let limit = limit.clamp(1, 5_000) as usize;
    let offset = offset as usize;

    let builder =
        ParquetRecordBatchStreamBuilder::new_with_metadata(reader, arrow_meta.clone());
    let columns: Vec<String> = builder
        .schema()
        .fields()
        .iter()
        .map(|f| f.name().to_string())
        .collect();

    // `with_offset`/`with_limit` push the row window into the reader so only the
    // touched row groups are fetched from S3.
    let mut stream = builder
        .with_offset(offset)
        .with_limit(limit)
        .build()
        .map_err(|e| format!("parquet stream: {e}"))?;

    let mut rows: Vec<Vec<Option<String>>> = Vec::new();
    while let Some(batch) = stream.next().await {
        let batch = batch.map_err(|e| format!("parquet batch: {e}"))?;
        let n = batch.num_rows();
        let cols = batch.columns();
        for r in 0..n {
            let mut cells = Vec::with_capacity(cols.len());
            for col in cols {
                cells.push(super::fs::data::arrow_value_to_string(col, r));
            }
            rows.push(cells);
        }
    }

    Ok(DataPreview {
        columns,
        rows,
        total: Some(file_total),
    })
}

// ---------------------------------------------------------------------------
// base64 (no extra dep — small std impl)
// ---------------------------------------------------------------------------

fn base64_encode(input: &[u8]) -> String {
    const T: &[u8; 64] = b"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";
    let mut out = String::with_capacity(input.len().div_ceil(3) * 4);
    for chunk in input.chunks(3) {
        let b = [
            chunk[0],
            *chunk.get(1).unwrap_or(&0),
            *chunk.get(2).unwrap_or(&0),
        ];
        let n = ((b[0] as u32) << 16) | ((b[1] as u32) << 8) | (b[2] as u32);
        out.push(T[((n >> 18) & 63) as usize] as char);
        out.push(T[((n >> 12) & 63) as usize] as char);
        out.push(if chunk.len() > 1 {
            T[((n >> 6) & 63) as usize] as char
        } else {
            '='
        });
        out.push(if chunk.len() > 2 {
            T[(n & 63) as usize] as char
        } else {
            '='
        });
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn base64_matches_known_vectors() {
        assert_eq!(base64_encode(b""), "");
        assert_eq!(base64_encode(b"f"), "Zg==");
        assert_eq!(base64_encode(b"fo"), "Zm8=");
        assert_eq!(base64_encode(b"foo"), "Zm9v");
        assert_eq!(base64_encode(b"foob"), "Zm9vYg==");
        assert_eq!(base64_encode(b"fooba"), "Zm9vYmE=");
        assert_eq!(base64_encode(b"foobar"), "Zm9vYmFy");
    }

    #[test]
    fn connection_roundtrips_without_secret_fields() {
        let c = S3Connection {
            id: "abc".into(),
            name: "prod".into(),
            region: "us-east-1".into(),
            endpoint: None,
            force_path_style: false,
            bucket: Some("data".into()),
        };
        let json = serde_json::to_string(&c).unwrap();
        assert!(!json.contains("secret"));
        assert!(!json.contains("access_key"));
        let back: S3Connection = serde_json::from_str(&json).unwrap();
        assert_eq!(back, c);
    }
}
